pipeline:
    name: Nginx
    identifier: Test
    projectIdentifier: Gittest
    orgIdentifier: CSE
    tags: {}
    stages:
        - stage:
              name: Nandeesh-test
              identifier: Nandeeshtest
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: k8skustomise
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: kustomise
                                        type: Kustomize
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.NandeeshGithub
                                                    gitFetchType: Branch
                                                    folderPath: kustomize/helloWorld
                                                    repoName: harness-docs
                                                    branch: main
                                            pluginPath: ""
                                            skipResourceVersioning: false
                  infrastructure:
                      environmentRef: devtest
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.k8s
                              namespace: nandeesh
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                          - step:
                                type: ShellScript
                                name: test
                                identifier: test
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo "test"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                    delegateSelectors:
                                        - test-docker
                                        - docker-delegate
                                timeout: 10m
                                failureStrategies: []
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
